apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: local-storage-operator
  namespace: openshift-local-storage
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  channel: stable
  installPlanApproval: Manual
  name: local-storage-operator
  source: redhat-operators # -> ミラーレジストリのCatalogSourceに変更
  sourceNamespace: openshift-marketplace
