apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-storage-resources
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: resources/local-storage-operator
    repoURL: https://github.com/kawano2687/gitops-sample.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true

