apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-resources
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: resources/opentelemetry-product
    repoURL: https://github.com/kawano2687/gitops-sample.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
  ignoreDifferences:
    - group: opentelemetry.io
      kind: OpenTelemetryCollector
      jsonPointers:
        - /spec/config/receivers/jaeger/protocols/grpc/endpoint
        - /spec/config/receivers/jaeger/protocols/thrift_binary/endpoint
        - /spec/config/receivers/jaeger/protocols/thrift_compact/endpoint
        - /spec/config/receivers/jaeger/protocols/thrift_http/endpoint
        - /spec/config/receivers/otlp/protocols/grpc/endpoint
        - /spec/config/receivers/otlp/protocols/http/endpoint
        - /spec/config/receivers/zipkin/endpoint
        - /spec/config/service/telemetry/metrics/address
