apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-operator
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  channel: stable-4.16
  installPlanApproval: Manual
  name: odf-operator
  source: redhat-operators # -> ミラーレジストリのCatalogSourceに変更
  sourceNamespace: openshift-marketplace
