apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  finalizers:
  - storage.openshift.com/local-volume-protection
  name: local-block
  namespace: openshift-local-storage
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  deviceInclusionSpec:
    deviceTypes:
    - disk
    minSize: 100Gi
  nodeSelector:
    nodeSelectorTerms:
     - matchExpressions:
       - key: cluster.ocs.openshift.io/openshift-storage
         operator: In
         values:
           - ""
  storageClassName: localblock
  volumeMode: Filesystem # -> NooBaaのDBコンポーネントではFilesystemを利用するため。
